[package]
name = "block_dsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest_derive = "2.1.0"
pest = "2.1.3"
serde = { version = "1", features = ["derive"] }
ts-rs = { version = "6.1" }
